#version 450

layout(std430, set = 0, binding = 0) buffer inbuffer 
{
    float idata[];
}inpData;

layout (local_size_x = 32) in;

layout(std430, set = 0, binding = 1) buffer obuffer 
{
    float odata[];
}outData;

layout (push_constant, std430) uniform pc
{
    int max_length;
};

void main() {
    int index = int(gl_GlobalInvocationID.x);
    if(index >= max_length)
        return;
	
	float v = inpData.idata[index];
	if (v < 0.0) {
	    v = 0.0;
	}
	
	outData.odata[index] = v;
}
